version: "3"

networks:
 pominovia-my-netology-hw:
   driver: bridge
   ipam:
     config:
     - subnet: 172.22.0.0/24

services:

 netology-db:
   image: postgres:latest
   container_name: pominovia-netology-db
   ports:
     - 5432:5432
   volumes:
     - ./pg_data:/var/lib/postgresql/data/pg_data
   environment:
     POSTGRES_PASSWORD: pominovia-12!3!!
     POSTGRES_DB: pominovia-POSTGRES_DB
     PGDATA: /var/lib/postgresql/data/pgdata
   networks:
     pominovia-my-netology-hw:
       ipv4_address: 172.22.0.2
   restart: always

 pgadmin:
   image: dpage/pgadmin4
   container_name: pominovia-pgamin
   ports:
     - 61231:80
   environment:
     PGADMIN_DEFAULT_EMAIL: pominovia@ilove-netology.com
     PGADMIN_DEFAULT_PASSWORD: 321654
   networks:
     pominovia-my-netology-hw:
       ipv4_address: 172.22.0.3
   restart: always

 zabbix-server:
   image: zabbix/zabbix-server-pgsql
   links:
     - netology-db
   container_name: pominovia-zabbix-netology
   environment:
     DB_SERVER_HOST: '172.22.0.2'
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: pominovia-12!3!!
   ports:
     - 10051:10051
   networks:
     pominovia-my-netology-hw:
       ipv4_address: 172.22.0.4
   restart: always

 zabbix_wgui:
   image: zabbix/zabbix-web-apache-pgsql
   links:
     - netology-db
     - zabbix-server
   container_name: pominovia-netology-zabbix-frontend
   environment:
     DB_SERVER_HOST: '172.22.0.2'
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: pominovia-12!3!!
     ZBX_SERVER_HOST: zabbix_wgui
     PHP_TZ: "Europe/Moscow"
   ports:
     - 80:8080
     - 443:8443
   networks:
     pominovia-my-netology-hw:
       ipv4_address: 172.22.0.5
   restart: always
